//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChargeNet_APP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChargeNet_APP.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;chargerReference&quot;:&quot;8&quot;,&quot;longitude&quot;:&quot;79.889851&quot;,&quot;latitude&quot;:&quot;6.860892&quot;,&quot;gpsLocation&quot;:&quot;Piliyandala Road, Kohuwela&quot;,&quot;workingStatus&quot;:&quot;FREE&quot;,&quot;locationName&quot;:&quot;SPKCHG2&quot;},{&quot;chargerReference&quot;:&quot;C0001&quot;,&quot;longitude&quot;:&quot;79.861156&quot;,&quot;latitude&quot;:&quot;6.929267&quot;,&quot;gpsLocation&quot;:&quot;Trace Expert City, Maradana, 0115 551 551&quot;,&quot;workingStatus&quot;:&quot;FREE&quot;,&quot;locationName&quot;:&quot;Trace&quot;},{&quot;chargerReference&quot;:&quot;C0002&quot;,&quot;longitude&quot;:&quot;79.860615&quot;,&quot;latitude&quot;:&quot;6.929651&quot;,&quot;gpsLocation&quot;:&quot;Trace Expert City, Maradana, 0115 551 551&quot;,&quot;workingStatus&quot;:&quot;IN_PROGRESS&quot;,&quot;locatio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string offlinejson {
            get {
                return ResourceManager.GetString("offlinejson", resourceCulture);
            }
        }
    }
}
